#!/usr/bin/env sh

# Run tests and exit if tests failed
./run_tests.sh
RESULT=$?
[ $RESULT -ne 0 ] && exit 1

# Checks for dbg! macros still left in the code
grep --exclude-dir cli/runtime_files 'dbg!' --exclude-dir .githooks --exclude-dir target -R . &&
  echo 'COMMIT REJECTED Found dbg statements. Please remove them before committing.' &&
  exit 1
# Checks for TODOs still left in the code
grep --exclude-dir cli/runtime_files 'TODO:' --exclude-dir .githooks --exclude-dir target -R . &&
  echo 'COMMIT REJECTED Found TODOs. Please remove them before committing.' &&
  exit 1

exit 0
