[workspace]

members = [
    "plojo_input_geminipr",
    "plojo_input_stdin",
    "plojo_core",
    "plojo_standard",
    "plojo_output_enigo",
    "plojo_output_macos",
    "cli",
    "telemetry",
    "lookup",
]

default-members = ["cli"]
