[workspace]

members = [
    "plojo_input_geminipr",
    "plojo_input_stdin",
    "plojo_core",
    "plojo_standard",
    "plojo_output_enigo",
    "plojo_output_autopilot",
    "plojo_output_applescript",
    "cli",
]
